name: iOS CI

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ iOS ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          scheme: ${{ 'Sample' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild clean test -project Sample.xcodeproj
