name: iOS CI

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ iOS ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          xcodebuild test -projec Sample/Sample.xcodeproj -scheme SampleTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12 mini,OS=14.0"
