name: iOS CI

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ iOS ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    env:
      project: ${{ 'Sample/Sample.xcodeproj' }}
      scheme: ${{ 'SampleTests' }}
      platform: ${{ 'iOS Simulator' }}
      simulator: ${{ 'iPhone 11 pro' }}
      os: ${{ 'latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          xcodebuild test -project "$project" -scheme "$scheme" -sdk iphonesimulator -destination "platform=$platform,name=$simulator,OS=$os"
      - name: If fail
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.issues.createComment({
              ...context.repo,
              issue_number: pull_number,
              body: "테스트가 실패하였습니다."
              })
        if: failure()
