name: iOS CI

on:
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ iOS ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    env:
      project: ${{ 'Sample/Sample.xcodeproj' }}
      scheme: ${{ 'SampleTests' }}
      platform: ${{ 'iOS Simulator' }}
      simulator: ${{ 'iPhone 11 pro' }}
      os: ${{ '14.0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          xcodebuild test -project "$project" -scheme "$scheme" -sdk iphonesimulator -destination "platform=$platform,name=$simulator,OS=$os"
      - uses: codecov/codecov-action@v1.0.14
        with:
          token: 19b182b3-bd34-42f4-9aa5-5deb1b80c414
      - name: If fail
        uses: peter-evans/create-or-update-comment@v1.4.3
        with:
          comment: 'This PR is the bees knees!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
